- hosts: localhost
  name: ONTAP
  gather_facts: false
  collections:
    - netapp.ontap
  tasks:
  - name: "Create SVM {{ src_svm }}"
    na_ontap_svm:
      state: present
      name: "{{ src_svm }}"
      root_volume: "svm_{{ src_svm }}_root"
      root_volume_aggregate: "{{ aggr_name }}"
      hostname: "{{ src_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  - name: "Configure DNS for Domain {{ domainname }}"
    na_ontap_dns:
      state: present
      vserver:  "{{ src_svm }}"
      domains: "{{ domainname }}"
      nameservers: "{{ nameserver }}"
      skip_validation: true
      hostname: "{{ src_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  - name: "Create {{ src_lifrole }} lif svm_{{ src_svm }}_data_LIF"
    na_ontap_interface:
      state: present
      vserver: "{{ src_svm }}"
      interface_name: "svm_{{ src_svm }}_data_LIF"
      home_port: "{{ src_lifhomeport }}"
      home_node: "{{ src_lifhomenode }}"
      role: "{{ src_lifrole }}"
      protocols: "{{ src_lifprotocol }}"
      admin_status: up
      is_auto_revert: true
      address: "{{ src_lifaddress }}"
      netmask: "{{ src_lifnetmask }}"
#      dns_domain_name: "{{ domainname }}"
      hostname: "{{ src_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  - name: "Create NFS Server on vserver {{src_svm}}"
    na_ontap_nfs:
      state: present
      service_state: started
      vserver: "{{ src_svm }}"
      nfsv3: "{{ nfsv3 }}"
      nfsv4: "{{ nfsv4 }}"
      nfsv41: disabled
      vstorage_state: enabled
      hostname: "{{ src_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
