- hosts: localhost
  name: ONTAP
  gather_facts: false
  collections:
    - netapp.ontap
  tasks:
  - name: Create the Export Policy
    na_ontap_export_policy:
      state: present
      name: "{{ src_volname }}"
      vserver: "{{ src_svm }}"
      hostname: "{{ src_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  - name: Create Export rules 
    na_ontap_export_policy_rule:
      state: present
      policy_name: "{{ src_volname }}"
      vserver: "{{ src_svm }}"
      client_match: "{{ client_match }}"
      ro_rule: any
      rw_rule: any
      super_user_security: any 
      hostname: "{{ src_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  - name: "Create Volume {{ src_volname }}"
    na_ontap_volume:
      state: present
      name: "{{ src_volname }}"
      size: "{{ volsize }}"
      size_unit: "gb"
      space_guarantee: none
      aggregate_name: "{{ src_aggrname }}"
      vserver: "{{ src_svm }}"
      junction_path: "/{{ src_volname }}"
      volume_security_style: unix
      hostname: "{{ src_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false

