- hosts: localhost
  name: ONTAP
  gather_facts: false
  collections:
    - netapp.ontap
  tasks:
  - name: "Create SVM {{ dr_svm }}"
    na_ontap_svm:
      state: present
      name: "{{ dr_svm }}"
      root_volume: "svm_{{ dr_svm }}_root"
      root_volume_aggregate: "{{ aggr_name }}"
      hostname: "{{ dr_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  - name: "Configure DNS for Domain {{ domainname }}"
    na_ontap_dns:
      state: present
      vserver:  "{{ dr_svm }}"
      domains: "{{ domainname }}"
      nameservers: "{{ nameserver }}"
      skip_validation: true
      hostname: "{{ dr_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  - name: "Create {{ dr_lifrole }} lif svm_{{ dr_svm }}_data_LIF"
    na_ontap_interface:
      state: present
      vserver: "{{ dr_svm }}"
      interface_name: "svm_{{ dr_svm }}_data_LIF"
      home_port: "{{ dr_lifhomeport }}"
      home_node: "{{ dr_lifhomenode }}"
      role: "{{ dr_lifrole }}"
      protocols: "{{ dr_lifprotocol }}"
      admin_status: up
      is_auto_revert: true
      address: "{{ dr_lifaddress }}"
      netmask: "{{ dr_lifnetmask }}"
#      dns_domain_name: "{{ domainname }}"
      hostname: "{{ dr_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  - name: "Create NFS Server on vserver {{dr_svm}}"
    na_ontap_nfs:
      state: present
      service_state: started
      vserver: "{{ dr_svm }}"
      nfsv3: "{{ nfsv3 }}"
      nfsv4: "{{ nfsv4 }}"
      nfsv41: disabled
      vstorage_state: enabled
      hostname: "{{ dr_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  - name: Create Vserver peer
    na_ontap_vserver_peer:
      state: present
      peer_vserver: "{{src_svm}}"
      peer_cluster: "{{src_clustername}}"
      dest_hostname: "{{src_cluster }}"
      vserver: "{{dr_svm}}"
      applications: snapmirror
      hostname: "{{dr_cluster}}"
      username: "{{ netapp_username }}"
      https: true
      password: "{{ netapp_password }}"
      validate_certs: false
